service: episodes-api

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource:
        - { "Fn::GetAtt": ["VoteData", "Arn"] }

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  get:
    handler: bin/get
    events:
      - http:
          path: /{name}
          method: get
          request:
            parameter:
              paths:
                name: true
  post:
    handler: bin/post
    events:
      - http:
          path: /
          method: post

resources:
  Resources:
    VoteData:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: episodes-vote-data
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: episodeId
            AttributeType: S
          - AttributeName: seriesId
            AttributeType: S
          - AttributeName: votes
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: seriesId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
